# Preprocesado de los datos

## Hecho por el equipo 1

Juan Francisco, Marc Uguet, Alvaro Carrasco y Ignacio Casado

## Imports

In [1]:
import pandas as pd
import datetime

## Funciones

In [2]:
def moreInfo(df):
    print(df.info())
    print("\n--------------\nNulos: "+str(df.isna().sum().sum())+"\n")
    print(df.isna().sum())

## Carga de datos

In [3]:
df_dcwe = pd.read_csv("daily_calendar_with_events.csv")
df_itpr = pd.read_csv("item_prices.csv")
df_itsa = pd.read_csv("item_sales.csv")

## Daily Calendar with Events

In [4]:
df_dcwe

date    weekday  weekday_int       d event
0     2011-01-29   Saturday            1     d_1   NaN
1     2011-01-30     Sunday            2     d_2   NaN
2     2011-01-31     Monday            3     d_3   NaN
3     2011-02-01    Tuesday            4     d_4   NaN
4     2011-02-02  Wednesday            5     d_5   NaN
...          ...        ...          ...     ...   ...
1908  2016-04-20  Wednesday            5  d_1909   NaN
1909  2016-04-21   Thursday            6  d_1910   NaN
1910  2016-04-22     Friday            7  d_1911   NaN
1911  2016-04-23   Saturday            1  d_1912   NaN
1912  2016-04-24     Sunday            2  d_1913   NaN

[1913 rows x 5 columns]

In [5]:
moreInfo(df_dcwe)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1913 entries, 0 to 1912
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   date         1913 non-null   object
 1   weekday      1913 non-null   object
 2   weekday_int  1913 non-null   int64 
 3   d            1913 non-null   object
 4   event        26 non-null     object
dtypes: int64(1), object(4)
memory usage: 74.9+ KB
None

--------------
Nulos: 1887

date              0
weekday           0
weekday_int       0
d                 0
event          1887
dtype: int64


Al ver que la columna "date" no tenía el dtype que debería (datetime), por lo que lo cambiamos.

Y cuando tengamos la columna "date" con el dtype correcto tendremos que sacar su propio "yearweek", los nulos de la columna "event" serán tratados más adelante

In [6]:
df_dcwe["date"] = pd.to_datetime(df_dcwe["date"], format="%Y-%m-%d")
df_dcwe["yearweek"] = df_dcwe["date"].dt.strftime("%Y%W").astype(float)

df_dcwe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1913 entries, 0 to 1912
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype         
---  ------       --------------  -----         
 0   date         1913 non-null   datetime64[ns]
 1   weekday      1913 non-null   object        
 2   weekday_int  1913 non-null   int64         
 3   d            1913 non-null   object        
 4   event        26 non-null     object        
 5   yearweek     1913 non-null   float64       
dtypes: datetime64[ns](1), float64(1), int64(1), object(3)
memory usage: 89.8+ KB


In [7]:
df_dcwe

date    weekday  weekday_int       d event  yearweek
0    2011-01-29   Saturday            1     d_1   NaN  201104.0
1    2011-01-30     Sunday            2     d_2   NaN  201104.0
2    2011-01-31     Monday            3     d_3   NaN  201105.0
3    2011-02-01    Tuesday            4     d_4   NaN  201105.0
4    2011-02-02  Wednesday            5     d_5   NaN  201105.0
...         ...        ...          ...     ...   ...       ...
1908 2016-04-20  Wednesday            5  d_1909   NaN  201616.0
1909 2016-04-21   Thursday            6  d_1910   NaN  201616.0
1910 2016-04-22     Friday            7  d_1911   NaN  201616.0
1911 2016-04-23   Saturday            1  d_1912   NaN  201616.0
1912 2016-04-24     Sunday            2  d_1913   NaN  201616.0

[1913 rows x 6 columns]

## Item Prices

In [8]:
df_itpr

item     category store_code  yearweek  sell_price
0         ACCESORIES_1_001   ACCESORIES      NYC_1  201328.0     12.7414
1         ACCESORIES_1_001   ACCESORIES      NYC_1  201329.0     12.7414
2         ACCESORIES_1_001   ACCESORIES      NYC_1  201330.0     10.9858
3         ACCESORIES_1_001   ACCESORIES      NYC_1  201331.0     10.9858
4         ACCESORIES_1_001   ACCESORIES      NYC_1  201332.0     10.9858
...                    ...          ...        ...       ...         ...
6965701  SUPERMARKET_3_827  SUPERMARKET      PHI_3       NaN      1.2000
6965702  SUPERMARKET_3_827  SUPERMARKET      PHI_3       NaN      1.2000
6965703  SUPERMARKET_3_827  SUPERMARKET      PHI_3       NaN      1.2000
6965704  SUPERMARKET_3_827  SUPERMARKET      PHI_3       NaN      1.2000
6965705  SUPERMARKET_3_827  SUPERMARKET      PHI_3       NaN      1.2000

[6965706 rows x 5 columns]

In [9]:
moreInfo(df_itpr)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6965706 entries, 0 to 6965705
Data columns (total 5 columns):
 #   Column      Dtype  
---  ------      -----  
 0   item        object 
 1   category    object 
 2   store_code  object 
 3   yearweek    float64
 4   sell_price  float64
dtypes: float64(2), object(3)
memory usage: 265.7+ MB
None

--------------
Nulos: 243920

item               0
category           0
store_code         0
yearweek      243920
sell_price         0
dtype: int64


In [10]:
df_itpr[df_itpr["yearweek"].isna()].index.to_list()[:20]

[149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 416,
 417,
 418,
 419,
 420,
 421,
 422,
 423,
 543,
 544,
 545,
 546]

Podemos ver que tiene 8 nulos seguidos en los algunos indices, por lo que veremos que hay antes y despues de esos indices con nulos

In [11]:
df_itpr.iloc[147:159]

item    category store_code  yearweek  sell_price
147  ACCESORIES_1_001  ACCESORIES      NYC_1  201616.0     11.1454
148  ACCESORIES_1_001  ACCESORIES      NYC_1  201617.0     11.1454
149  ACCESORIES_1_001  ACCESORIES      NYC_1       NaN     11.1454
150  ACCESORIES_1_001  ACCESORIES      NYC_1       NaN     11.1454
151  ACCESORIES_1_001  ACCESORIES      NYC_1       NaN     11.1454
152  ACCESORIES_1_001  ACCESORIES      NYC_1       NaN     11.1454
153  ACCESORIES_1_001  ACCESORIES      NYC_1       NaN     11.1454
154  ACCESORIES_1_001  ACCESORIES      NYC_1       NaN     11.1454
155  ACCESORIES_1_001  ACCESORIES      NYC_1       NaN     11.1454
156  ACCESORIES_1_001  ACCESORIES      NYC_1       NaN     11.1454
157  ACCESORIES_1_002  ACCESORIES      NYC_1  201125.0      5.2801
158  ACCESORIES_1_002  ACCESORIES      NYC_1  201126.0      5.2801

In [12]:
df_itpr.iloc[8841:8853]

item    category store_code  yearweek  sell_price
8841  ACCESORIES_1_036  ACCESORIES      NYC_1  201616.0      1.4896
8842  ACCESORIES_1_036  ACCESORIES      NYC_1  201617.0      1.4896
8843  ACCESORIES_1_036  ACCESORIES      NYC_1       NaN      1.4896
8844  ACCESORIES_1_036  ACCESORIES      NYC_1       NaN      1.4896
8845  ACCESORIES_1_036  ACCESORIES      NYC_1       NaN      1.4896
8846  ACCESORIES_1_036  ACCESORIES      NYC_1       NaN      1.4896
8847  ACCESORIES_1_036  ACCESORIES      NYC_1       NaN      1.4896
8848  ACCESORIES_1_036  ACCESORIES      NYC_1       NaN      1.4896
8849  ACCESORIES_1_036  ACCESORIES      NYC_1       NaN      1.4896
8850  ACCESORIES_1_036  ACCESORIES      NYC_1       NaN      1.4896
8851  ACCESORIES_1_037  ACCESORIES      NYC_1  201211.0     17.2501
8852  ACCESORIES_1_037  ACCESORIES      NYC_1  201212.0     17.2501

Parece ser los items tienen el yearweek nulo en sus ultimos 8 rows de cada uno

In [13]:
df_itpr["item"].nunique()

3049

In [14]:
df_itpr["store_code"].nunique()

10

Tenemos 3049 items unicos y podemos ver los store_code tienen 10 valores unicos

Sabiendo que teniamos 243920 nulos en yearweek, comprobaremos si todos los items tienen 8 nulos, calculando:

**(items x veces que aparecen) x 8 nulos**

In [15]:
# Nos devolvera True en caso de que el 
# calculo nos de la misma cantidad de 
# nulos que teniamos en yearweek

(3049*10)*8 == 243920

True

## Item Sales

In [16]:
df_itsa

id               item     category     department  \
0       ACCESORIES_1_001_NYC_1   ACCESORIES_1_001   ACCESORIES   ACCESORIES_1   
1       ACCESORIES_1_002_NYC_1   ACCESORIES_1_002   ACCESORIES   ACCESORIES_1   
2       ACCESORIES_1_003_NYC_1   ACCESORIES_1_003   ACCESORIES   ACCESORIES_1   
3       ACCESORIES_1_004_NYC_1   ACCESORIES_1_004   ACCESORIES   ACCESORIES_1   
4       ACCESORIES_1_005_NYC_1   ACCESORIES_1_005   ACCESORIES   ACCESORIES_1   
...                        ...                ...          ...            ...   
30485  SUPERMARKET_3_823_PHI_3  SUPERMARKET_3_823  SUPERMARKET  SUPERMARKET_3   
30486  SUPERMARKET_3_824_PHI_3  SUPERMARKET_3_824  SUPERMARKET  SUPERMARKET_3   
30487  SUPERMARKET_3_825_PHI_3  SUPERMARKET_3_825  SUPERMARKET  SUPERMARKET_3   
30488  SUPERMARKET_3_826_PHI_3  SUPERMARKET_3_826  SUPERMARKET  SUPERMARKET_3   
30489  SUPERMARKET_3_827_PHI_3  SUPERMARKET_3_827  SUPERMARKET  SUPERMARKET_3   

                   store store_code        region  d_1  d_2  d_3  ...  d_1904  \
0      Greenwich_Village      NYC_1      New York    0    0    0  ...       1   
1      Greenwich_Village      NYC_1      New York    0    0    0  ...       0   
2      Greenwich_Village      NYC_1      New York    0    0    0  ...       2   
3      Greenwich_Village      NYC_1      New York    0    0    0  ...       1   
4      Greenwich_Village      NYC_1      New York    0    0    0  ...       2   
...                  ...        ...           ...  ...  ...  ...  ...     ...   
30485      Queen_Village      PHI_3  Philadelphia    0    0    2  ...       2   
30486      Queen_Village      PHI_3  Philadelphia    0    0    0  ...       0   
30487      Queen_Village      PHI_3  Philadelphia    0    6    0  ...       2   
30488      Queen_Village      PHI_3  Philadelphia    0    0    0  ...       0   
30489      Queen_Village      PHI_3  Philadelphia    0    0    0  ...       0   

       d_1905  d_1906  d_1907  d_1908  d_1909  d_1910  d_1911  d_1912  d_1913  
0           3       0       1       1       1       3       0       1       1  
1           0       0       0       0       1       0       0       0       0  
2           1       2       1       1       1       0       1       1       1  
3           0       5       4       1       0       1       3       7       2  
4           1       1       0       1       1       2       2       2       4  
...       ...     ...     ...     ...     ...     ...     ...     ...     ...  
30485       0       0       0       0       0       1       0       0       1  
30486       0       0       0       0       0       0       0       1       0  
30487       1       0       2       0       1       0       0       1       0  
30488       0       1       0       0       1       0       3       1       3  
30489       0       0       0       0       0       0       0       0       0  

[30490 rows x 1920 columns]

In [17]:
moreInfo(df_itsa)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30490 entries, 0 to 30489
Columns: 1920 entries, id to d_1913
dtypes: int64(1913), object(7)
memory usage: 446.6+ MB
None

--------------
Nulos: 0

id            0
item          0
category      0
department    0
store         0
             ..
d_1909        0
d_1910        0
d_1911        0
d_1912        0
d_1913        0
Length: 1920, dtype: int64


In [18]:
list_days = [x for x in df_itsa.columns.to_list() if x.startswith("d_")]
list_columns = [x for x in df_itsa.columns.to_list() if not x.startswith("d_")]

df_sales = pd.melt(df_itsa, id_vars=list_columns, value_vars=list_days, 
                   var_name="d", value_name="n_sales")


In [19]:
df_sales

id               item     category  \
0          ACCESORIES_1_001_NYC_1   ACCESORIES_1_001   ACCESORIES   
1          ACCESORIES_1_002_NYC_1   ACCESORIES_1_002   ACCESORIES   
2          ACCESORIES_1_003_NYC_1   ACCESORIES_1_003   ACCESORIES   
3          ACCESORIES_1_004_NYC_1   ACCESORIES_1_004   ACCESORIES   
4          ACCESORIES_1_005_NYC_1   ACCESORIES_1_005   ACCESORIES   
...                           ...                ...          ...   
58327365  SUPERMARKET_3_823_PHI_3  SUPERMARKET_3_823  SUPERMARKET   
58327366  SUPERMARKET_3_824_PHI_3  SUPERMARKET_3_824  SUPERMARKET   
58327367  SUPERMARKET_3_825_PHI_3  SUPERMARKET_3_825  SUPERMARKET   
58327368  SUPERMARKET_3_826_PHI_3  SUPERMARKET_3_826  SUPERMARKET   
58327369  SUPERMARKET_3_827_PHI_3  SUPERMARKET_3_827  SUPERMARKET   

             department              store store_code        region       d  \
0          ACCESORIES_1  Greenwich_Village      NYC_1      New York     d_1   
1          ACCESORIES_1  Greenwich_Village      NYC_1      New York     d_1   
2          ACCESORIES_1  Greenwich_Village      NYC_1      New York     d_1   
3          ACCESORIES_1  Greenwich_Village      NYC_1      New York     d_1   
4          ACCESORIES_1  Greenwich_Village      NYC_1      New York     d_1   
...                 ...                ...        ...           ...     ...   
58327365  SUPERMARKET_3      Queen_Village      PHI_3  Philadelphia  d_1913   
58327366  SUPERMARKET_3      Queen_Village      PHI_3  Philadelphia  d_1913   
58327367  SUPERMARKET_3      Queen_Village      PHI_3  Philadelphia  d_1913   
58327368  SUPERMARKET_3      Queen_Village      PHI_3  Philadelphia  d_1913   
58327369  SUPERMARKET_3      Queen_Village      PHI_3  Philadelphia  d_1913   

          n_sales  
0               0  
1               0  
2               0  
3               0  
4               0  
...           ...  
58327365        1  
58327366        0  
58327367        0  
58327368        3  
58327369        0  

[58327370 rows x 9 columns]

In [20]:
moreInfo(df_sales)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58327370 entries, 0 to 58327369
Data columns (total 9 columns):
 #   Column      Dtype 
---  ------      ----- 
 0   id          object
 1   item        object
 2   category    object
 3   department  object
 4   store       object
 5   store_code  object
 6   region      object
 7   d           object
 8   n_sales     int64 
dtypes: int64(1), object(8)
memory usage: 3.9+ GB
None

--------------
Nulos: 0

id            0
item          0
category      0
department    0
store         0
store_code    0
region        0
d             0
n_sales       0
dtype: int64


## Merging DFs

### Merge de Item Prices con Daily Calendar with Events

In [21]:
df_merged = pd.merge(df_itpr, 
                     df_dcwe[["date","d","yearweek", "event"]], 
                     how="left",
                     on="yearweek")

### Merge de df_merged con df_sales

In [22]:
df_completo = pd.merge(df_sales[["id","item","category","department","store_code",
                                "region","d","n_sales"]],
                    df_merged[["item","category","store_code","yearweek","date",
                                "d","sell_price", "event"]], 
                    how="left",
                    on=["item","category","store_code","d"])

In [23]:
moreInfo(df_completo)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 58327370 entries, 0 to 58327369
Data columns (total 12 columns):
 #   Column      Dtype         
---  ------      -----         
 0   id          object        
 1   item        object        
 2   category    object        
 3   department  object        
 4   store_code  object        
 5   region      object        
 6   d           object        
 7   n_sales     int64         
 8   yearweek    float64       
 9   date        datetime64[ns]
 10  sell_price  float64       
 11  event       object        
dtypes: datetime64[ns](1), float64(2), int64(1), object(8)
memory usage: 5.6+ GB
None

--------------
Nulos: 94774409

id                   0
item                 0
category             0
department           0
store_code           0
region               0
d                    0
n_sales              0
yearweek      12360393
date          12360393
sell_price    12360393
event         57693230
dtype: int64


In [25]:
df_completo

id               item     category  \
0          ACCESORIES_1_001_NYC_1   ACCESORIES_1_001   ACCESORIES   
1          ACCESORIES_1_002_NYC_1   ACCESORIES_1_002   ACCESORIES   
2          ACCESORIES_1_003_NYC_1   ACCESORIES_1_003   ACCESORIES   
3          ACCESORIES_1_004_NYC_1   ACCESORIES_1_004   ACCESORIES   
4          ACCESORIES_1_005_NYC_1   ACCESORIES_1_005   ACCESORIES   
...                           ...                ...          ...   
58327365  SUPERMARKET_3_823_PHI_3  SUPERMARKET_3_823  SUPERMARKET   
58327366  SUPERMARKET_3_824_PHI_3  SUPERMARKET_3_824  SUPERMARKET   
58327367  SUPERMARKET_3_825_PHI_3  SUPERMARKET_3_825  SUPERMARKET   
58327368  SUPERMARKET_3_826_PHI_3  SUPERMARKET_3_826  SUPERMARKET   
58327369  SUPERMARKET_3_827_PHI_3  SUPERMARKET_3_827  SUPERMARKET   

             department store_code        region       d  n_sales  yearweek  \
0          ACCESORIES_1      NYC_1      New York     d_1        0       NaN   
1          ACCESORIES_1      NYC_1      New York     d_1        0       NaN   
2          ACCESORIES_1      NYC_1      New York     d_1        0       NaN   
3          ACCESORIES_1      NYC_1      New York     d_1        0       NaN   
4          ACCESORIES_1      NYC_1      New York     d_1        0       NaN   
...                 ...        ...           ...     ...      ...       ...   
58327365  SUPERMARKET_3      PHI_3  Philadelphia  d_1913        1  201616.0   
58327366  SUPERMARKET_3      PHI_3  Philadelphia  d_1913        0  201616.0   
58327367  SUPERMARKET_3      PHI_3  Philadelphia  d_1913        0  201616.0   
58327368  SUPERMARKET_3      PHI_3  Philadelphia  d_1913        3  201616.0   
58327369  SUPERMARKET_3      PHI_3  Philadelphia  d_1913        0  201616.0   

               date  sell_price event  
0               NaT         NaN   NaN  
1               NaT         NaN   NaN  
2               NaT         NaN   NaN  
3               NaT         NaN   NaN  
4               NaT         NaN   NaN  
...             ...         ...   ...  
58327365 2016-04-24       3.576   NaN  
58327366 2016-04-24       2.976   NaN  
58327367 2016-04-24       4.776   NaN  
58327368 2016-04-24       1.536   NaN  
58327369 2016-04-24       1.200   NaN  

[58327370 rows x 12 columns]

## Últimas transformaciones

Al ver que nuestro dataframe tenía date con nulos (cuando deberían tener un valor relacionado con la columna "d") pues decidimos crear un dataframe con el que podríamos conseguir las fechas faltantes y sustituir la columna "date" original por una que no tuviera nulos y se basara en la columna "d".

In [26]:
list_un_d = df_completo["d"].unique()

dates = pd.date_range(start=df_completo["date"].min(), 
                      periods=len(list_un_d), 
                      freq="D")

date_mapping = pd.DataFrame({"d": list_un_d,"date": dates})

df = pd.merge(df_completo[[
    "id",
    "item",
    "category",
    "department",
    "store_code",
    "region",
    "event",
    "d",
    "n_sales",
    "sell_price"
 ]], 
 date_mapping, on="d", how="left")

df.drop("d", axis=1, inplace=True)

In [27]:
df

id               item     category  \
0          ACCESORIES_1_001_NYC_1   ACCESORIES_1_001   ACCESORIES   
1          ACCESORIES_1_002_NYC_1   ACCESORIES_1_002   ACCESORIES   
2          ACCESORIES_1_003_NYC_1   ACCESORIES_1_003   ACCESORIES   
3          ACCESORIES_1_004_NYC_1   ACCESORIES_1_004   ACCESORIES   
4          ACCESORIES_1_005_NYC_1   ACCESORIES_1_005   ACCESORIES   
...                           ...                ...          ...   
58327365  SUPERMARKET_3_823_PHI_3  SUPERMARKET_3_823  SUPERMARKET   
58327366  SUPERMARKET_3_824_PHI_3  SUPERMARKET_3_824  SUPERMARKET   
58327367  SUPERMARKET_3_825_PHI_3  SUPERMARKET_3_825  SUPERMARKET   
58327368  SUPERMARKET_3_826_PHI_3  SUPERMARKET_3_826  SUPERMARKET   
58327369  SUPERMARKET_3_827_PHI_3  SUPERMARKET_3_827  SUPERMARKET   

             department store_code        region event  n_sales  sell_price  \
0          ACCESORIES_1      NYC_1      New York   NaN        0         NaN   
1          ACCESORIES_1      NYC_1      New York   NaN        0         NaN   
2          ACCESORIES_1      NYC_1      New York   NaN        0         NaN   
3          ACCESORIES_1      NYC_1      New York   NaN        0         NaN   
4          ACCESORIES_1      NYC_1      New York   NaN        0         NaN   
...                 ...        ...           ...   ...      ...         ...   
58327365  SUPERMARKET_3      PHI_3  Philadelphia   NaN        1       3.576   
58327366  SUPERMARKET_3      PHI_3  Philadelphia   NaN        0       2.976   
58327367  SUPERMARKET_3      PHI_3  Philadelphia   NaN        0       4.776   
58327368  SUPERMARKET_3      PHI_3  Philadelphia   NaN        3       1.536   
58327369  SUPERMARKET_3      PHI_3  Philadelphia   NaN        0       1.200   

               date  
0        2011-01-31  
1        2011-01-31  
2        2011-01-31  
3        2011-01-31  
4        2011-01-31  
...             ...  
58327365 2016-04-26  
58327366 2016-04-26  
58327367 2016-04-26  
58327368 2016-04-26  
58327369 2016-04-26  

[58327370 rows x 10 columns]

Aun nos quedaban unos problemas pendientes y eran rellenar los nulos en la columna "event" y crear una columna para poder graficar las ganancias en una visualización, la cual cálculamos multiplicando el precio del producto por el número de ventas.

In [28]:
df["event"].fillna("none", inplace=True)
df["sell_price"] = df.groupby("id")["sell_price"].bfill()
df["sell_price"] = round(df["sell_price"], 2)
df["revenues"] = round(df["sell_price"] * df["n_sales"], 2)

## Dataframe final

In [29]:
df

id               item     category  \
0          ACCESORIES_1_001_NYC_1   ACCESORIES_1_001   ACCESORIES   
1          ACCESORIES_1_002_NYC_1   ACCESORIES_1_002   ACCESORIES   
2          ACCESORIES_1_003_NYC_1   ACCESORIES_1_003   ACCESORIES   
3          ACCESORIES_1_004_NYC_1   ACCESORIES_1_004   ACCESORIES   
4          ACCESORIES_1_005_NYC_1   ACCESORIES_1_005   ACCESORIES   
...                           ...                ...          ...   
58327365  SUPERMARKET_3_823_PHI_3  SUPERMARKET_3_823  SUPERMARKET   
58327366  SUPERMARKET_3_824_PHI_3  SUPERMARKET_3_824  SUPERMARKET   
58327367  SUPERMARKET_3_825_PHI_3  SUPERMARKET_3_825  SUPERMARKET   
58327368  SUPERMARKET_3_826_PHI_3  SUPERMARKET_3_826  SUPERMARKET   
58327369  SUPERMARKET_3_827_PHI_3  SUPERMARKET_3_827  SUPERMARKET   

             department store_code        region event  n_sales  sell_price  \
0          ACCESORIES_1      NYC_1      New York  none        0       12.74   
1          ACCESORIES_1      NYC_1      New York  none        0        5.28   
2          ACCESORIES_1      NYC_1      New York  none        0        3.95   
3          ACCESORIES_1      NYC_1      New York  none        0        5.77   
4          ACCESORIES_1      NYC_1      New York  none        0        3.96   
...                 ...        ...           ...   ...      ...         ...   
58327365  SUPERMARKET_3      PHI_3  Philadelphia  none        1        3.58   
58327366  SUPERMARKET_3      PHI_3  Philadelphia  none        0        2.98   
58327367  SUPERMARKET_3      PHI_3  Philadelphia  none        0        4.78   
58327368  SUPERMARKET_3      PHI_3  Philadelphia  none        3        1.54   
58327369  SUPERMARKET_3      PHI_3  Philadelphia  none        0        1.20   

               date  revenues  
0        2011-01-31      0.00  
1        2011-01-31      0.00  
2        2011-01-31      0.00  
3        2011-01-31      0.00  
4        2011-01-31      0.00  
...             ...       ...  
58327365 2016-04-26      3.58  
58327366 2016-04-26      0.00  
58327367 2016-04-26      0.00  
58327368 2016-04-26      4.62  
58327369 2016-04-26      0.00  

[58327370 rows x 11 columns]

In [30]:
moreInfo(df)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 58327370 entries, 0 to 58327369
Data columns (total 11 columns):
 #   Column      Dtype         
---  ------      -----         
 0   id          object        
 1   item        object        
 2   category    object        
 3   department  object        
 4   store_code  object        
 5   region      object        
 6   event       object        
 7   n_sales     int64         
 8   sell_price  float64       
 9   date        datetime64[ns]
 10  revenues    float64       
dtypes: datetime64[ns](1), float64(2), int64(1), object(7)
memory usage: 5.2+ GB
None

--------------
Nulos: 0

id            0
item          0
category      0
department    0
store_code    0
region        0
event         0
n_sales       0
sell_price    0
date          0
revenues      0
dtype: int64


In [31]:
print(df.describe().T)
print(df.describe(include="object").T)
print("\nDate")
print("min:", df["date"].min())
print("max:", df["date"].max())

                 count      mean        std   min   25%   50%   75%      max
n_sales     58327370.0  1.126322   3.873108  0.00  0.00  0.00  1.00   763.00
sell_price  58327370.0  5.563519   4.547548  0.01  2.62  4.18  7.18   134.15
revenues    58327370.0  3.961199  11.831317  0.00  0.00  0.00  3.63  2598.48
               count unique                     top      freq
id          58327370  30490  ACCESORIES_1_001_NYC_1      1913
item        58327370   3049        ACCESORIES_1_001     19130
category    58327370      3             SUPERMARKET  27489810
department  58327370      7           SUPERMARKET_3  15743990
store_code  58327370     10                   NYC_1   5832737
region      58327370      3                New York  23330948
event       58327370      6                    none  57693230

Date
min: 2011-01-31 00:00:00
max: 2016-04-26 00:00:00


## Creación del CSV para las visualizaciones con PowerBI

In [32]:
df.to_csv("processed_data_for_viz.csv")